export class Lecturer {
    lecturer_id?: number;              // Optional for new lecturers as it will be auto-generated by the database
    lecturerName: string;
    lecturerExperience: string;
    lecturerDegrees: string;
    lecturerImageName?: string;
    lecturerImageType?: string;
    lecturerImageData?: string;       // Store image data as a Base64 encoded string if needed
    facultyId?: number;               // To associate lecturer with a specific faculty
  
    constructor(
      lecturerName: string,
      lecturerExperience: string,
      lecturerDegrees: string,
      lecturerImageName?: string,
      lecturerImageType?: string,
      lecturerImageData?: string,
      facultyId?: number
    ) {
      this.lecturerName = lecturerName;
      this.lecturerExperience = lecturerExperience;
      this.lecturerDegrees = lecturerDegrees;
      this.lecturerImageName = lecturerImageName;
      this.lecturerImageType = lecturerImageType;
      this.lecturerImageData = lecturerImageData;
      this.facultyId = facultyId;
    }
  }
  