export class Register {
  reg_id?: number = undefined;
  program: string = '';
  title: string = '';
  referral: string = '';
  shortName: string = '';
  fullName: string = '';
  dob: string = '';
  country: string = '';
  passport: string = '';
  mobile: string = '';
  email: string = '';
  address: string = '';
  username: string = '';
  password: string = '';
  faculty: any = {};
  imageData?: string = '';
  imageName?: string = '';
  imageType?: string = '';
}
